# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: pinedax
email: 
subtitle: Un blog de una persona normal.
description: >- # this means to ignore newlines until "baseurl:"
  Hola 👋, mi nombre es Andres Pineda y soy un desarrollador de aplicaciones.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pinedax_dev
github_username:  apinedax
name: Andres Pineda
author:
  name: Andres Pineda
  location: Republica Dominicana
  avatar: /assets/images/profile.png
  teaser: /assets/images/profile.png
  repository: apinedax/apinedax.github.io
twitter:
  username: pinedax_dev
  card: summary_large_image
social:
  name: Andres Pineda
  links:
    - https://twitter.com/pinedax_dev
    - https://github.com/apinedax

# Build settings
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "aqua"
locale: "es"
search: true
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/profile.png
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      show_date: true
      author_profile: true
      related: true
      toc: true
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
